name: Pull requests
on: pull_request
jobs:
  TestAffectedProjects:
    runs-on: ubuntu-latest
    name: 'Test affected projects'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build core
        run: yarn workspace @centipod/core run build
      - name: Build CLI
        run: yarn workspace @centipod/cli run build
      - name: Lint codebase
        run: yarn lint
      - name: Build packages using himself
        run: yarn build
      - name: Test packages
        run: yarn test
