name: update-doc

run-name: Update documentation

on:
  push:
    branches:
      - ci/release-bot

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: touch test-action
      - run: git add test-action
      - run: git status
      - run: 'git commit -S -m"test: release bot" --no-verify'
      - run: git push --no-verify
